# Generated by Django 3.2.12 on 2022-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='company_address',
            field=models.TextField(default=' testest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='company_logo',
            field=models.ImageField(default='test.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='company_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
