# Generated by Django 4.0.3 on 2022-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminconfig',
            options={'verbose_name': 'Admin Config', 'verbose_name_plural': 'Admin Config'},
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='working_days',
            field=models.CharField(max_length=100),
        ),
    ]
