# Generated by Django 3.2.12 on 2022-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0002_auto_20220416_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='company_name',
        ),
    ]
