# Generated by Django 4.0.3 on 2022-04-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0002_alter_adminconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('MN', 'Monday'), ('TU', 'Tuesday'), ('WD', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('ST', 'Saturday'), ('SN', 'Sunday')], max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='working_days',
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='working_days',
            field=models.ManyToManyField(to='admin_system.workingday'),
        ),
    ]
