# Generated by Django 4.0.3 on 2022-04-03 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0003_workingday_remove_adminconfig_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='end_time',
            field=models.TimeField(default=datetime.time(2, 11, 5, 248770)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='start_time',
            field=models.TimeField(default=datetime.time(2, 11, 10, 804594)),
            preserve_default=False,
        ),
    ]
