# Generated by Django 4.0.3 on 2022-04-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0004_adminconfig_end_time_adminconfig_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminconfig',
            name='working_days',
        ),
    ]
