# Generated by Django 3.2.12 on 2022-04-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0005_alter_workingday_day_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminconfig',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workingday',
            name='updated_at',
        ),
    ]
