# Generated by Django 3.2.12 on 2022-04-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0005_remove_adminconfig_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workingday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
