# Generated by Django 3.2.12 on 2022-04-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0006_auto_20220417_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingday',
            old_name='day_name',
            new_name='day',
        ),
    ]
