# Generated by Django 3.2.12 on 2022-04-16 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.DateField(auto_created=True, default=employee.models.get_now_date)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('brand_of_device', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('wage_per_hour', models.FloatField()),
                ('contact_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, default=None, null=True)),
                ('brand_of_device', models.CharField(max_length=150)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
