# Generated by Django 4.0.3 on 2022-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
