# Generated by Django 4.0.3 on 2022-04-03 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_mac_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='gross_salary',
            new_name='wage_per_hour',
        ),
        migrations.AddField(
            model_name='employee',
            name='brand_of_device',
            field=models.CharField(default='iPhone', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(default='0321 1234567', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2022, 4, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.date(2022, 4, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='last name', max_length=100),
            preserve_default=False,
        ),
    ]
