# Generated by Django 3.2.12 on 2022-04-14 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_partialemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialemployee',
            name='applied',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 4, 14)),
            preserve_default=False,
        ),
    ]
