# Generated by Django 3.2.12 on 2022-04-15 06:15

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_partialemployee_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partialemployee",
            name="applied",
            field=models.DateField(
                auto_created=True, default=employee.models.get_now_date
            ),
        ),
    ]
