# Generated by Django 3.2.12 on 2022-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_partialemployee_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialemployee',
            name='applied',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
