# Generated by Django 3.2.12 on 2022-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_partialemployee_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialemployee',
            name='contact',
            field=models.CharField(default='+92 321 1234567', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialemployee',
            name='ip',
            field=models.CharField(default='192.168.0.1', max_length=50),
            preserve_default=False,
        ),
    ]
