# Generated by Django 3.2.12 on 2022-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_partialemployee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='wage_per_hour',
            field=models.FloatField(),
        ),
    ]
