# Generated by Django 3.2.12 on 2022-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('ip', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=17)),
            ],
        ),
    ]
