# Generated by Django 3.2.12 on 2022-04-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='updated_at',
        ),
    ]
