# Generated by Django 3.2.12 on 2022-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_auto_20220416_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='type',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='repeats',
            field=models.BooleanField(default=True),
        ),
    ]
