# Generated by Django 4.0.3 on 2022-04-03 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_in',
            field=models.TimeField(auto_created=True, default=datetime.time(19, 39, 56, 249386)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='checked_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
