# Generated by Django 3.2.12 on 2022-04-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_leaves_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
