# Generated by Django 3.2.12 on 2022-04-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_leave_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Early', 'Early'), ('Present', 'Present'), ('Late', 'Late')], max_length=10),
        ),
    ]
