# Generated by Django 3.2.12 on 2022-04-20 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checked_in',
            field=models.TimeField(default=datetime.time(2, 44, 49, 512639)),
            preserve_default=False,
        ),
    ]
