# Generated by Django 3.2.12 on 2022-04-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checked_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
